export const CAR_CONFIG = {
  spawn: {
    position: { x: 72, y: 0.48, z: 34 },
    heading: Math.PI / 2
  },
  maxSpeed: 66,
  maxReverseSpeed: 8.5,
  acceleration: 18.8,
  accelerationMinRatio: 0.2,
  brakePower: 28,
  brakeForce: 28,
  reverseAcceleration: 10.5,
  directionChangeBrakeThreshold: 0.42,
  friction: 0.24,
  coastDrag: 0.24,
  offRoadDrag: 0.24,
  offRoadRollingResistance: 1.05,
  offRoadGrip: 0.58,
  offRoadAccelerationRatio: 0.82,
  offRoadBrakeRatio: 0.72,
  offRoadTurnRatio: 0.64,
  offRoadVelocityAlignmentRatio: 0.42,
  offRoadDriftBuildRatio: 1.35,
  offRoadMaxSlipAngleMultiplier: 1.75,
  offRoadSlipStartSpeed: 13,
  surfaceProbeMargin: 1.15,
  rollingResistance: 0.85,
  stopSnapSpeed: 0.08,
  steeringResponse: 4.8,
  steeringReturnSpeed: 6.6,
  turnSpeed: 1.62,
  minSteerSpeed: 1.3,
  lowSpeedTurnBoost: 1.22,
  lowSpeedTurnBoostSpeed: 10,
  highSpeedTurnStart: 22,
  highSpeedTurnRatio: 0.26,
  driftStartSpeed: 22,
  driftFullSpeed: 58,
  driftSteerThreshold: 0.72,
  driftBuildRate: 1.8,
  driftDecayRate: 4.6,
  velocityAlignment: 12,
  driftAlignment: 4.8,
  maxSlipAngle: 0.38,
  collisionSlowdown: 0.16,
  collisionBounceMaxSpeed: 3.2,
  collisionSlideRetention: 0.48,
  collisionSteeringRetention: 0.28,
  nitroCapacity: 100,
  nitroBoost: 1.18,
  nitroDrainRate: 34,
  nitroRechargeRate: 13,
  nitroMinSpeed: 2,
  nitroMaxSpeedMultiplier: 1.16,
  collisionRadius: 1.45,
  collisionSkin: 0.08,
  maxSurfaceDrop: 2.2,
  safePointClearance: 1.35,
  autoRecoverDelay: 1.8,
  stuckMoveEpsilon: 0.08,
  slopeAttitudeResponse: 8,
  visualLean: 0.055,
  simulationStep: 1 / 60,
  simulationMaxFrameDelta: 0.3,
  telemetryInterval: 0.08
};
