import { BoxInstances, CylinderInstances, PlaneInstances } from '../rendering/instanceRenderers.jsx';

export function RoadLayers({ batches, worldMaterials }) {
  return (
    <>
      <PlaneInstances
        name="HighwayInstances"
        color={worldMaterials.highway.color}
        instances={batches.highways}
        metalness={worldMaterials.roadMetalness}
        roughness={worldMaterials.roadRoughness}
        receiveShadow
      />
      <PlaneInstances
        name="RampRoadInstances"
        color={worldMaterials.highway.color}
        instances={batches.rampRoads}
        metalness={worldMaterials.roadMetalness}
        receiveShadow
        roughness={worldMaterials.roadRoughness}
      />
      <PlaneInstances
        name="MainRoadInstances"
        color={worldMaterials.mainRoad.color}
        instances={batches.mainRoads}
        metalness={worldMaterials.roadMetalness}
        roughness={worldMaterials.roadRoughness}
        receiveShadow
      />
      <PlaneInstances
        name="LocalRoadInstances"
        color={worldMaterials.localRoad.color}
        instances={batches.localRoads}
        metalness={worldMaterials.roadMetalness}
        roughness={worldMaterials.localRoad.roughness}
        receiveShadow
      />
      <PlaneInstances
        name="ParkingLotInstances"
        color={worldMaterials.parking.color}
        instances={batches.parkingLots}
        metalness={worldMaterials.roadMetalness}
        roughness={worldMaterials.parking.roughness}
        receiveShadow
      />
      <CylinderInstances
        name="RoundaboutAsphaltInstances"
        color={worldMaterials.roundabout.color}
        instances={batches.roundabouts}
        radialSegments={24}
        receiveShadow
        roughness={worldMaterials.roadRoughness}
      />
      <CylinderInstances
        name="RoundaboutIslandInstances"
        color={worldMaterials.roundaboutIsland.color}
        instances={batches.roundaboutIslands}
        radialSegments={18}
        receiveShadow
        roughness={worldMaterials.roundaboutIsland.roughness}
      />
      <BoxInstances
        name="RoadEdgeDirtInstances"
        color={worldMaterials.roadDirt.color}
        depthWrite={false}
        instances={batches.roadEdgeDirt}
        materialType="basic"
        opacity={worldMaterials.roadDirt.opacity}
        transparent
      />
      <BoxInstances
        name="RoadWearMarkInstances"
        color={worldMaterials.roadWear.color}
        depthWrite={false}
        instances={batches.roadWearMarks}
        materialType="basic"
        opacity={worldMaterials.roadWear.opacity}
        transparent
      />
      <BoxInstances
        name="RoadCrackMarkInstances"
        color={worldMaterials.roadCrack.color}
        depthWrite={false}
        instances={batches.roadCrackMarks}
        materialType="basic"
        opacity={worldMaterials.roadCrack.opacity}
        transparent
      />
      <BoxInstances
        name="LaneMarkInstances"
        color={worldMaterials.markings.color}
        instances={batches.laneMarks}
        materialType="standard"
        receiveShadow
        roughness={worldMaterials.markings.roughness}
      />
      <BoxInstances
        name="YellowLaneMarkInstances"
        color="#ffd21f"
        instances={batches.laneMarksYellow}
        materialType="basic"
        roughness={worldMaterials.markings.roughness}
        toneMapped={false}
      />
      <BoxInstances
        name="ParkingMarkInstances"
        color="#cfd6d6"
        instances={batches.parkingMarks}
        materialType="standard"
        receiveShadow
        roughness={0.76}
      />
      <BoxInstances
        name="RoadCurbInstances"
        color={worldMaterials.curb.color}
        instances={batches.roadCurbs}
        materialType="standard"
        receiveShadow
        roughness={worldMaterials.curb.roughness}
      />
      <BoxInstances
        name="SidewalkInstances"
        color={worldMaterials.sidewalk.color}
        instances={batches.sidewalks}
        materialType="standard"
        receiveShadow
        roughness={worldMaterials.sidewalk.roughness}
      />
      <BoxInstances
        name="SidewalkRailInstances"
        color={worldMaterials.sidewalkRail.color}
        instances={batches.sidewalkRails}
        materialType="standard"
        castShadow
        receiveShadow
        roughness={worldMaterials.sidewalkRail.roughness}
      />
      <BoxInstances
        name="MedianBarrierInstances"
        color={worldMaterials.medianBarrier.color}
        instances={batches.medianBarriers}
        materialType="standard"
        castShadow
        receiveShadow
        roughness={worldMaterials.medianBarrier.roughness}
      />
      <BoxInstances
        name="CrosswalkMarkInstances"
        color="#e7dfc9"
        instances={batches.crosswalkMarks}
        materialType="standard"
        receiveShadow
        roughness={0.72}
      />
      <BoxInstances
        name="StopBarInstances"
        color="#d7d0bb"
        instances={batches.stopBars}
        materialType="standard"
        receiveShadow
        roughness={0.74}
      />
    </>
  );
}
