import { ConeInstances, CylinderInstances, PlaneInstances } from '../rendering/instanceRenderers.jsx';

export function TerrainLayers({ batches, worldMaterials }) {
  return (
    <>
      <PlaneInstances
        name="GroundInstances"
        color={worldMaterials.ground.color}
        instances={batches.ground}
        metalness={worldMaterials.ground.metalness}
        roughness={worldMaterials.ground.roughness}
        receiveShadow
      />
      <PlaneInstances
        name="WaterInstances"
        color={worldMaterials.water.color}
        instances={batches.waterAreas}
        metalness={worldMaterials.water.metalness}
        roughness={worldMaterials.water.roughness}
        receiveShadow
      />
      <CylinderInstances
        name="IslandGroundInstances"
        color={worldMaterials.island.color}
        instances={batches.islandGrounds}
        radialSegments={28}
        receiveShadow
        roughness={worldMaterials.island.roughness}
      />
      <ConeInstances
        name="MountainPeakInstances"
        color="#6f8d66"
        instances={batches.mountainPeaks}
        radialSegments={14}
        castShadow
        receiveShadow
        roughness={0.95}
      />
      <ConeInstances
        name="HillMoundInstances"
        color="#7fb36e"
        instances={batches.hillMounds}
        radialSegments={20}
        receiveShadow
        roughness={0.96}
      />
      <CylinderInstances
        name="BasinFloorInstances"
        color="#56736b"
        instances={batches.basinFloors}
        radialSegments={32}
        receiveShadow
        roughness={0.98}
      />
    </>
  );
}
